language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - "~/.platformio"
install:
- pip install -U platformio
- platformio update
script:
- mkdir build
- platformio ci --keep-build-dir --build-dir ./build --project-conf=platformio.ini
  src/main.cpp
before_deploy:
- platformio ci -h
- ls -a
- find . -name "*.bin"
deploy:
  provider: releases
  api_key:
    secure: jGwDe9LIptWZeqoO0UtO8TpON/BWWItjM819PWdPBfXtLf5jOkbekUyg1U9MqWQt7/hIYKDaMHpLfalaPyEChNMDoEgicGKwtEGq09lIjrQZo9SwOHMU8xNK50OFCr5akqBSozuKoPEOW8nhG78wGbLkTpGbrzqKgVP65l+QfI8wZjNmM5sYWyvePffkP+Daxb6uk51yjdQ0QloOYdLW5XjHM9SHn6CSxBe3a1YpWMSZedfQNLAWxbEToTuIzXiK8CyyQH1Lno6AEjcLMLtE3Pm6SvGuxhindzrwQ2FBI/35cLYtclqcwSIJz1mMyhEzSpTRbDQzsoQDx0OokzZsVrBdVYSv3AbativSnUqw6/Z2l7Ei0vUchOPhDAwEvj54rvR2ylELeYC86agQ5d4kWCQBRSmU0sA0HOBq7rmHt5AmwHVbGYHmGuFmNqwlKKXE7RtXdLFZH4c04sfhPfNx2V4Z9rLyKtXsC1nbY8mcmvSaXu1HBUBVzekbI9gwHQaImUT4uql0uhcNF9AbSJC1pWL41i0g5WOIs/Hmem9ia+z2o8BDdES4qm46snp0U1lBDtCKtv9mB2TUV4W+i9qPA+DnZQZUHkClHxbhFEMlQGD3XtR9BG0fsxaLWw+mPul2/BgDk7QVygdy+WkUmWMj7MMDDZyFSELyzMkiqANDia0=
  file: "./build/.pio/build/esp32cam/firmware.bin"
  on:
    repo: IoTDevice/ESP32-CAM
    tags: true
